datopian/gift-publisher

- package.json
- yarn.lock
> Add Github page builder

- src/App.css
- src/App.js
This pull request adds style to the progress screen
> [App][s]: style the progress screen

- src/App.css
- src/App.js
- src/components/Upload/index.jsx
> [Action button][m]: Remove back btn and next btn from first screen

- src/App.js
- src/components/Metadata/Metadata.css
- src/components/Metadata/Metadata.test.js
- src/components/Metadata/index.jsx
- src/components/TableSchema/TableSchema.test.js
- src/components/TableSchema/index.jsx
> Cleanup UI

- cypress.json
- cypress/fixtures/sample.csv
- cypress/integration/publisher-spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- package.json
- public/index.html
- src/App.js
- src/components/Upload/index.jsx
- src/mock.js
- yarn.lock
This pull request integrate upload method to `gift-publisher` base on #21
> Lfs upload

- src/App.js
> [datapackage] [s] : update datapackage info upload

- src/App.js
This pull removes the default resource state variable from App.js
> [App][s]: Remove auto-created resource from state

- src/App.js
- src/index.js
This pull fixes download and save issue
> [App.js][m]:Fix last screen download bug

- src/App.js
- src/components/TablePreview/index.jsx
- src/components/Upload/index.jsx
- src/index.js
> Add sample property to datapackage state

- src/App.js
> Fix resource removal bug

- package.json
- src/App.css
- src/App.js
- src/components/Metadata/Metadata.css
- src/components/Metadata/index.jsx
- src/components/Upload/index.jsx
- src/db/countries.json
- yarn.lock
> Redesign the component to make it easier to use and to show only relevant information

- src/App.js
- src/components/Upload/Upload.css
- src/components/Upload/index.jsx
- src/utils/index.js
>  Add/link an existing file

- src/components/TableSchema/index.jsx
This pull request ensure Title field, Description field, and Richtype field is filled before moving to the next step base on issue from gift-portal: https://github.com/datopian/gift-publisher/issues/42
> Schema Field

- src/App.js
- src/index.js
> [Metadata][s]: Update publisher to skip to metadata screen

- package.json
- src/App.js
- src/components/Metadata/index.jsx
- yarn.lock
> [Tags][m]: Remove tagify lib and use vanilla JS to generate tags

- src/App.js
- src/components/Metadata/Metadata.css
- src/components/Metadata/index.jsx
> Refactor metadata and update fields

- src/App.js
- src/components/Metadata/index.jsx
> [Metadata][m]: Fix existing metadata fields display

- src/App.js
This pull updates the remove resource route in order to fix https://github.com/datopian/gift-portal/issues/153
> [App.js][m]: Update remove resource method

- README.md
- src/App.js
- src/components/Metadata/index.jsx
- src/components/ResourceList/index.jsx
- src/components/TableSchema/index.jsx
- src/components/Upload/index.jsx
- src/lib/components/DatasetEditor/index.js
- src/lib/components/Metadata/index.js
- src/lib/components/Upload/index.js
@steveoni, could you have a look at this one, please? :wink:
> [README,typos][l]: Fix typos, reformat

- src/App.js
- src/components/Upload/index.jsx
> [Datapackage][m]: Remove sample and schema from top level data package

- src/components/Metadata/index.jsx
> [metadata][m]: Add image property to metadata

- src/components/TableSchema/index.jsx
> [TableSchema][m]: Set title and description fields as optional

- src/components/Metadata/index.jsx
This PR fixes https://github.com/datopian/gift-publisher/issues/77
> [Metadata][s]: Update level of govt fields

- src/App.js
- src/components/Metadata/Metadata.css
- src/components/Metadata/index.jsx
> [Metadata][m]: Update tags with tooltip and validation

- src/components/TableSchema/index.jsx
- src/components/Upload/index.jsx
> Fix existing type display

- src/App.js
- src/components/TableSchema/index.jsx
> Richtype combination and validation

- src/App.js
- src/components/Upload/index.jsx
This pr implemented the feature as requested here #95
> Create a copy of uploaded file without csv
